modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/RainShield/issues"
license="MIT"

[[mods]]
modId="rainshield"
version="${file.jarVersion}"
displayName="Rain Shield"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rain-shield"
authors="Mrbysco"
description='''
Just a simple mod adding a Rain Shield
'''
[[dependencies.rainshield]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"