modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/RainShield/issues"
license="MIT"

[[mods]]
modId="rainshield"
version="${file.jarVersion}"
displayName="Rain Shield"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rain-shield"
authors="Mrbysco"
description='''
Just a simple mod adding a Rain Shield
'''
[[dependencies.rainshield]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.rainshield]]
modId="neoforge"
mandatory=true
versionRange="[20.2.59-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "rainshield.mixins.json"